# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-SimpleScan-Plugin-LinkCheck
version:      0.01
version_from: lib/App/SimpleScan/Plugin/LinkCheck.pm
installdirs:  site
requires:
    App::SimpleScan:               0
    Scalar::Util:                  0
    Test::More:                    0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
